Polish up for release
adafruit/Adafruit_CircuitPython_BLE_Eddystone pull request #1
Opened 2020-02-14 22:48 UTC by tannewt

2020-02-14 23:58 UTC, dhalbert requested changes
I'm not so keen on some of black's changes, like double quotes for single quotes or uppercasing hex constants, but oh well.

2020-02-14 23:58 UTC, dhalbert commented on adafruit_ble_eddystone/url.py
> +    b".edu" b".net",
Missing comma here, I think.

2020-02-14 23:58 UTC, dhalbert commented on adafruit_ble_eddystone/url.py
> +    b".edu" b".net",
it got reformatted to one line.

2020-02-19 18:31 UTC, tannewt commented
This is blocked on https://github.com/adafruit/Adafruit_Blinka_bleio/pull/1 which will introduce a richer `_bleio`

2020-02-19 20:47 UTC, dhalbert approved these changes
Looks good!

2020-02-19 20:47 UTC, merged